- .eslintrc.js
- app/(tabs)/_layout.tsx
- app/(tabs)/explore.tsx
- app/(tabs)/index.tsx
- app/+html.tsx
- app/+not-found.tsx
- app/_layout.tsx
- babel.config.js
- components/Collapsible.tsx
- components/ExternalLink.tsx
- components/HelloWave.tsx
- components/ParallaxScrollView.tsx
- components/ThemedText.tsx
- components/ThemedView.tsx
- components/__tests__/ThemedText-test.tsx
- components/navigation/TabBarIcon.tsx
- constants/Colors.ts
- hooks/useColorScheme.ts
- hooks/useColorScheme.web.ts
- hooks/useThemeColor.ts
- package-lock.json
- package.json
- scripts/reset-project.js
hab alles hinzugefügt und gleich einmal den prettier alles formatieren lassen
> Linter und Prettier eingebunden

- app.json
- eas.json
- package-lock.json
- package.json
Ich habe auch an ein paar Stellen den Namen der App auf 1001km geändert.
> Zusätzliche Konfiguration um die App zu bauen

- app.json
- eas.json
- package-lock.json
- package.json
Hab vergessen eas update für das Projekt zu konfigurieren. Deswegen ging es nicht.
> eas update dem Projekt hinzufügen

- app/(tabs)/(touren)/[tourId].tsx
- app/_layout.tsx
- components/Tour/StageCard.tsx
- components/Tour/StageList.tsx
- constants/custom-theme.ts
Die Farben sind jetzt in einem gemeinsamen "foofTheme". Dieses wird von "foofDarkTheme" und "foofLightTheme" gespreadet und durch z.B. Hintergrundfarben ergänzt.
Außerdem habe ich noch kurz die Etappenliste verbessert, was Farben und Level anging.
> GPLR-112 White Mode Implementierung

- model/database_functions.ts
- services/tracking.ts
> GPLR-144 [Bug] Endzeit nicht gesetzt beim Stoppen von Etappen

- app/(tabs)/_layout.tsx
https://github.com/user-attachments/assets/6a45cf45-7fad-4df2-8c64-ea8d0dfe7e76
> UI Kitten Tabbar

- services/tracking.ts
> fix avg speed by setting finishAt before calculating avg speed

- .github/workflows/tests.yml
> add --passWithNoTests

- app.json
- app/(tabs)/(touren)/index.tsx
- components/Statistics/TourStats.tsx
- components/Tour/StageCard.tsx
- components/Tour/TourList.tsx
- package-lock.json
- package.json
- services/sharingService.ts
- services/statisticsService.ts
- utils/__tests__/dateUtil-test.ts
- utils/dateUtil.ts
Idee: Auf der Seite wo die Karte der Route angezeigt wird, kann man seine Tour teilen
Vorerst würde ich dann die Karte mit dem Share Knopf ersetzen, und wenn die Karte gemacht wird, dann können wir ja wieder zurückswitchen
Weitere Infos dazu in Jira
> Gprl 100 etappe und tour teilen

- app/(tabs)/(home)/index.tsx
> Mapbox Label auf System Sprache anzeigen

- app.json
- app/(tabs)/(home)/index.tsx
- package-lock.json
- package.json
- services/tracking.ts
> Gplr 131 tracking auf foreground umbauen

- services/data/stageService.ts
- services/tracking.ts
> Fix no active stage set

- services/tracking.ts
> Notification geändert

- services/tracking.ts
> Average Speed for Stage

- components/Statistics/TourStats.tsx
- components/Statistics/__tests__/TourStats-test.tsx
- components/Statistics/__tests__/__snapshots__/TourStats-test.tsx.snap
- database/model/model.ts
- services/data/stageService.ts
- services/tracking.ts
> GPLR 169 Tourstatistik reaktiv machen

- app/(tabs)/(home)/index.tsx
Ich hab die style props entfernet, da diese sowieso immer leer sind
> GPLR 172 Knopf Ganze Route sehen soll nicht angezeigt werden wenn keine Route importiert ist

- app/(tabs)/(touren)/_layout.tsx
> changed the name of the page in layout

- app/(tabs)/(touren)/_layout.tsx
- app/(tabs)/(touren)/stagesMapViewWrapper.tsx
- app/(tabs)/(touren)/tourSettings.tsx
- components/Map/MapWithMarkers.tsx
- components/Map/Marker.tsx
- components/Route/RenderRoute.tsx
- components/TopNavigation/renderBackAction.tsx
- components/Tour/StagesMapView.tsx
Ich hab das Aussehen der Linien von RenderRoute an die anderen Linien von StageMapLine angepasst. Feedback zu den Farben wäre gut.
> GPLR-159 Tourroutenplanung Route auf Tour Karte anzeigen 

- app/_layout.tsx
> GPLR-212 Status-Bar-Farbe-wird-nicht-von-der-App-gesteuert

- app/(tabs)/(touren)/__tests__/__snapshots__/index-test.tsx.snap
- app/(tabs)/(touren)/index.tsx
- components/Stage/__tests__/__snapshots__/StageStatCard-test.tsx.snap
- components/Statistics/IconStat.tsx
- components/Statistics/TourProgressBar.tsx
- components/Statistics/TourStats.tsx
- components/Statistics/__tests__/__snapshots__/IconStat-test.tsx.snap
- components/Statistics/__tests__/__snapshots__/TourProgressBar-test.tsx.snap
- components/Statistics/__tests__/__snapshots__/TourStats-test.tsx.snap
- components/Tour/__tests__/__snapshots__/StageCard-test.tsx.snap
- components/Tour/__tests__/__snapshots__/StageList-test.tsx.snap
- constants/custom-theme.ts
> Gplr 187 tourstatistik verschoenern

- app/_layout.tsx
- package-lock.json
- package.json
- test-utils/test-utils.tsx
> deleted unused fontawesome package

- package-lock.json
- package.json
> Version bumped

- app/(tabs)/(touren)/__tests__/__snapshots__/tourSettings-tests.tsx.snap
- app/(tabs)/(touren)/tourSettings.tsx
- components/Statistics/LiveStats.tsx
> Text Fixes

- app/(tabs)/(touren)/__tests__/__snapshots__/createManualStage-test.tsx.snap
- app/(tabs)/(touren)/__tests__/createManualStage-test.tsx
- app/(tabs)/(touren)/createManualStage.tsx
> Gplr 228 manuelle etappe koordinaten und karte vertauschen

- components/Map/StageMapView.tsx
- components/Stage/StageCard.tsx
- components/Stage/StageList.tsx
- components/Stage/StageStatCard.tsx
- components/Statistics/IconStat.tsx
- components/Statistics/LiveStats.tsx
- components/Statistics/TourStats.tsx
- constants/styles.ts
- database/index.ts
- services/data/locationService.ts
- services/data/routeService.ts
- services/manualStageInputService.ts
- services/sharingService.ts
- services/trackingService.ts
- test-utils/test-utils.tsx
- utils/locationUtils.ts
> Translate comments

- app.json
> update app version in app.json

- app/(tabs)/(home)/index.tsx
> fix navigation in onStopButtonPress

- app/(tabs)/(touren)/createManualStage.tsx
- components/Map/MapWithMarkers.tsx
- components/Map/StageMapLine.tsx
- components/Stage/__tests__/StageStatCard-test.tsx
- database/model/model.ts
- database/schemas/schema.ts
- services/StageConnection/__tests__/stageConnection-test.ts
- services/data/locationService.ts
- services/manualStageInputService.ts
- services/trackingService.ts
> fix task to account for multiple locations

- app/(tabs)/(touren)/__tests__/__snapshots__/index-test.tsx.snap
- components/Stage/__tests__/StageCard-test.tsx
- components/Stage/__tests__/__snapshots__/StageCard-test.tsx.snap
- services/sharingService.ts
- utils/__tests__/dateUtils-test.ts
- utils/dateUtils.ts
> Sharing Service fixed

- services/data/locationService.ts
- services/trackingService.ts
Globale Variablen sind immer kritisch. Wenn z.B. eine neue Location kommt und ein Location Batch noch nicht fertig ist, könnte es passieren, dass lastLocation überschrieben wird und die Berechnung der Distance schief geht.
> Fix race condition in tracking service

- components/Statistics/LiveStats.tsx
> show speed with one decimal place

- components/Map/MapWithMarkers.tsx
> call onCameraChanged only when map finished loading

- components/Map/MapWithMarkers.tsx
> call onCameraChanged only when map finished loading (#111)
